### ISSUE TITLE
vendoring files from scipy?

### ISSUE THREAD

**Issue by beckermr** [conda-forge/isce3-feedstock#18]
Something in this build is vendoring files from scipy according to our bots: https://github.com/conda-forge/artifact-validation/issues/769

Can you all look at this @conda-forge/isce3?

**Comment by rtburns-jpl** [comment]
```
tree lib/python3.7/site-packages/scipy/                                       
lib/python3.7/site-packages/scipy/
└── stats
    └── __pycache__
        └── _page_trend_test.cpython-37-pytest-6.2.5.pyc

2 directories, 1 file
```

I guess it's just the pycache that's created during unit tests. Shouldn't this be stripped out by the feedstock build? What do I need to do to get rid of it?

**Comment by beckermr** [comment]
Ahhhh. Do you run the tests during the build or test phase?

**Comment by beckermr** [comment]
Looks like build phase. conda-build won't remove those. If you can run them during the test phase that will fix it. Otherwise removing them by hand is fine.

**Comment by rtburns-jpl** [comment]
Oh I see, thanks! So instead of calling ctest in build.sh, I should put in meta.yaml:

```yaml
test:
  commands:
     ctest
```

Is that right?

**Comment by beckermr** [comment]
Yes. You umay need to request that conda build specific source files when doing this as well.
